# Generated by Django 3.2.7 on 2021-09-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
    ]
