# Generated by Django 3.2.7 on 2021-09-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_remove_user_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
    ]
