# Generated by Django 3.2.7 on 2021-09-01 15:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
