# Generated by Django 3.2.7 on 2021-09-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
