# Generated by Django 3.2.7 on 2021-09-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_auto_20210924_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='user/%Y/%m'),
        ),
    ]
