# Generated by Django 3.2.7 on 2021-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=None, upload_to='images/slider/%Y/%m'),
        ),
    ]
