# Generated by Django 3.2.7 on 2021-09-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_slider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default=None, upload_to='images/destinations/%Y/%m'),
        ),
    ]
