# Generated by Django 3.2.7 on 2021-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
