# Generated by Django 3.2.7 on 2021-10-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_tourdetail_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_date',
        ),
    ]
