# Generated by Django 3.2.7 on 2021-10-13 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_remove_booking_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 13, 4, 4, 6, 420548, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 13, 4, 4, 13, 557660, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
