# Generated by Django 3.2.7 on 2021-10-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20211013_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
